### ISSUE TITLE
Publishing records -- Solr commit fail

### ISSUE THREAD

**Issue by deletedname** [ewg118/xEAC#7]
Hi Ethan,
When we try to publish records from the editing interface, we get an error message: Solr commit failed. We are running Solr 4.10.4. Unsure what the issue is, Jen and I are looking at the Tomcat logs where we are seeing:

> SolrCore Initialization Failures
> Cannot create directory
> SolrResourceLoader
> Can't find (or read) directory to add to classloader

Also, when we try to publish individual records, the check box under "Publish" remains unchanged. Are these related issues?

If you need additional info from me, let me know.
Thanks,
Iris

**Comment by ewg118** [comment]
They are likely related. Were you previously able to publish records before you deployed the newest xEAC code?

**Comment by deletedname** [comment]
I don't think I published anything before the update. We rolled it back to test -- good news -- the publish link works. But, we got this response when trying to publish an individual record:

> Data failed to POST to Solr. Index may be offline or URL is incorrect.


We are also getting the same Solr commit fail when trying to publish all records.

What do you think is going on? Did we miss a step in the installation process?

**Comment by ewg118** [comment]
It's probably something simple. It might be easier to troubleshoot over email.

**Comment by deletedname** [comment]
Great, thanks!

**Comment by ewg118** [comment]
Okay, resolved. Fixed other issues regarding publication of EAC-CPF to Solr in the admin panel

**Comment by deletedname** [comment]
Many thanks for all your help!
