### ISSUE TITLE
Editing content in header and footer

### ISSUE THREAD

**Issue by deletedname** [ewg118/xEAC#8]
Hi Ethan,
Is there an easy way to add content into the header and footer?
I am in templates.xsl and cannot find the file referenced in:
```
<xsl:template name="footer">
        <xsl:copy-of select="//config/footer/*"/>
</xsl:template>
```
Also, I would like to add a logo graphic to the header, instead of displaying text (which I was able to edit in xEAC settings). Thanks for your help!
Iris

**Comment by ewg118** [comment]
I've never implemented an HTML editor in the xEAC settings page for editing the footer. If you have the eXist client, you can edit the content of the config.xml footer element directly (or access the admin panel or eXist client directly through the eXist dashboard, which is at http://servername:8080/exist). The footer element in config.xml just contains HTML. You can always edit the footer, header, or index page XSLT templates if there are significant design changes you want to implement.

**Comment by deletedname** [comment]
Got it. As a side note, I viewed the config.xml (opening it from the eXist admin panel) but the content was not the same as the xml file found in the program folder on my local drive. In any case I am able to edit the content using exide -- all is good!
Thanks again!

**Comment by ewg118** [comment]
No problem.
